server:
  port: 8082
  # Nginx가 SSL을 처리하므로 Spring Boot SSL 비활성화
  # ssl:
  #   enabled: true
  #   key-store: classpath:keystore.p12
  #   key-store-password: password123
  #   key-store-type: PKCS12
  #   key-alias: tomcat
  # http2:
  #   enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: hackathon-backend
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        webAllowOthers: true 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  
  security:
    user:
      name: admin
      password: admin123

# OpenAI API 설정
openai:
  api:
    key: ${OPENAI_API_KEY:dummy-key-for-testing}
    model: ${OPENAI_MODEL:gpt-4o-mini}
    max-tokens: ${OPENAI_MAX_TOKENS:200}

# 파일 업로드 설정
file:
  upload:
    max-size: ${MAX_FILE_SIZE:10485760}
    upload-dir: ${UPLOAD_DIR:uploads/}

# JWT 설정
jwt:
  secret: ${JWT_SECRET:your-secret-key-here}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.hackathon: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG  # CORS 로그 활성화
    org.springframework.web.filter: DEBUG  # 필터 로그 활성화

management:
  endpoints:
    web:
      exposure:
        include: health,info
