name: Build & Push to Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      
      - name: Setup Gradle 8.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5'

      - name: Build (Gradle)
        run: |
          echo "=== Gradle 설치 확인 ==="
          gradle --version
          echo "=== Gradle 빌드 시작 ==="
          gradle clean bootJar -x test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (latest + commit SHA)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: |
            leehoseung9227/hackathon-server:latest
            leehoseung9227/hackathon-server:${{ github.sha }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repository }}
