name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Maven 빌드 (테스트 제외)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 3. Docker 로그인 (DockerHub)
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/hackathon-server:latest
          docker build -t $IMAGE_NAME .

      # 5. Docker 이미지 푸시
      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/hackathon-server:latest
          docker push $IMAGE_NAME

      # 6. SSH로 서버 접속 후 Docker 컨테이너 재시작
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/hackathon
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hackathon-server:latest
            docker stop hackathon-server || true
            docker rm hackathon-server || true
            docker run -d --name hackathon-server -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/hackathon-server:latest
